//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCongTy
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanCong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhanCong()
        {
            this.NhanViens = new HashSet<NhanVien>();
        }
    
        public string MaDA { get; set; }
        public string MaCV { get; set; }
        public string MaNV { get; set; }
        public string MoTa { get; set; }
        public Nullable<System.DateTime> NgayBD { get; set; }
        public Nullable<System.DateTime> DeadLine { get; set; }
        public Nullable<int> TienDo { get; set; }
        public string Danhgia { get; set; }
        public Nullable<int> ChamDiem { get; set; }
        public Nullable<int> TienThuong { get; set; }
    
        public virtual CongViec CongViec { get; set; }
        public virtual DuAn DuAn { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanVien> NhanViens { get; set; }
    }
}
