//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCongTy
{
    using System;
    using System.Collections.Generic;
    
    public partial class XinNghi
    {
        public string MaNV { get; set; }
        public System.DateTime NgayNghi { get; set; }
        public Nullable<int> SoNgayNghi { get; set; }
        public string LyDo { get; set; }
        public int HeSoDuyet { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
